### ISSUE TITLE
Add support for protobuf 3.0

### ISSUE THREAD

**Issue by SRyabinin** [pseudomuto/protoc-gen-doc#17]
Hello Elvis,
Many thanks for you project at first.
Are you going to support new version of protobuf 3.0? I suppose it's near release.

**Comment by estan** [comment]
Hi @SRyabinin, as soon as 3.0 is released and packaged for the distributions that protoc-gen-doc supports, I'll see what it takes to update the tool. But it's good that you opened this issue to remind me. Thanks!

**Comment by skyao** [comment]
Looking forward to the new 1.0 version so that it can support proto3. I like this tool so much.

**Comment by skyao** [comment]
Just one question: do you have any time plan for 1.0 release? I would like to know that how long I will wait for it ~0~

**Comment by estan** [comment]
Hi @skyao , glad you like the tool.

1.0 will be released after protobuf 3.0.0 final has been released and reached into the package repositories for the distros the tool supports. This may take some time I'm afraid, and there's also #22 which I want fixed before I release 1.0.

I should probably start work on supporting 3.0.0 before it is released though, and once that happens you could of course use Git `master`. At the moment I'm a bit busy at work though. Of course, I accept pull requests :)

**Comment by rmartin7c** [comment]
@estan during our last interaction you explained to me that most of what this plugin does depends on protobuf parsing the input .proto files successfully. That led me to wonder whether or not the only problem was that I'd been building against libproto 2.6.1. So, just for giggles, I installed libprotobuf 3.0.0-beta3 on my Mac today, (brew install --devel protobuf) and built protoc-gen-doc against it. I got five -Wunused-parameter warnings, but it built. 

> In file included from src/main.cpp:37:
> /usr/local/opt/protobuf/include/google/protobuf/compiler/code_generator.h:100:65: warning: unused parameter 'files' [-Wunused-parameter]
>   virtual bool GenerateAll(const vector<const FileDescriptor*>& files,
>                                                                 ^
> /usr/local/opt/protobuf/include/google/protobuf/compiler/code_generator.h:101:42: warning: unused parameter 'parameter' [-Wunused-parameter]
>                            const string& parameter,
>                                          ^
> /usr/local/opt/protobuf/include/google/protobuf/compiler/code_generator.h:102:46: warning: unused parameter 'generator_context' [-Wunused-parameter]
>                            GeneratorContext* generator_context,
>                                              ^
> In file included from src/main.cpp:38:
> In file included from /usr/local/opt/protobuf/include/google/protobuf/descriptor.h:59:
> /usr/local/opt/protobuf/include/google/protobuf/stubs/shared_ptr.h:441:58: warning: unused parameter 'other' [-Wunused-parameter]
>   enable_shared_from_this(const enable_shared_from_this& other) { }
>                                                          ^
> /usr/local/opt/protobuf/include/google/protobuf/stubs/shared_ptr.h:442:69: warning: unused parameter 'other' [-Wunused-parameter]
>   enable_shared_from_this& operator=(const enable_shared_from_this& other) {

It appears to be working correctly, too. syntax="proto3" seems to be just fine, now. This does not look like it will be a challenging update, at all.

**Comment by estan** [comment]
So sorry for the very late reply, been very busy at work. Indeed what you describe and what I'd been suspecting is that the upgrade to protobuf 3 should be pretty smooth. I will do this upgrade once 3 is final and have a look then if there are any 3-specific features we want to support. In any case, there will have to be two binary versions supported across the platforms I support, one for 2 and one for 3, since I don't think ABI compatibility is maintained.

**Comment by rmartin7c** [comment]
Proto 3.0.0 released! :-) Finally!

https://github.com/google/protobuf/releases/tag/v3.0.0

**Comment by skyao** [comment]
Since v3.0.0 is released, we should make this tools work for it. 

@estan : Any roadmap for this?

**Comment by skyao** [comment]
@estan I have a good news for you that seems this plugin can work in proto v3.0.0 without any update.

I have tried in linux (mint linux 17.02, based on ubuntu 14.04):

1. I first installed proto-gen-doc by apt-get command, just as descripted in the document
2. then I removed the /usr/bin/protoc (which is 2.5.0 version) and /usr/include/google/protobuf
3. I downloaded the protoc of version v3.0.0 from protobuf site
4. I copy the files in this zip to  /usr/bin/protoc and /usr/include/google/protobuf
5. This proto-gen-doc plugin works!!

So, seems you just need to update the version from v2.5.0 to v3.0.0 and then you can  do the release.

**Comment by rmartin7c** [comment]
I've already built proto-gen-doc against protoc 3.0.0, and it works with no issues. I'm just waiting for official binary releases in Linux x86_64 and OSX flavors so I can track those in my local Artifactory instead of maintaining my own snapshot builds.

**Comment by tbillington** [comment]
If it can work against proto3, how can I get around this error.

```
query.proto:1:10: Unrecognized syntax identifier "proto3".  This parser only recognizes "proto2".
```

**Comment by rmartin7c** [comment]
@tbillington you have to make sure that you're binding against the proto 3.0.0 libraries, not any proto 2.x ones. On my Mac, I used homebrew to remove the old proto 2.6.1 installation and upgraded to proto 3.0.0. Then I cloned this project's source to my local and followed the instructions to build from source.

**Comment by jdaily** [comment]
This does compile with the latest proto version. However the documentation generated is misleading for many because in 3.0 `required` and `optional` was removed.

Might I recommend we set the default for `required` if the documentation is generated with 3.x?

**Comment by rmartin7c** [comment]
@jdaily I don't think that makes sense. Protobuf 3.0 doesn't support `required` at all. All fields are optional by default, so `optional` makes more sense as a default.

**Comment by jdaily** [comment]
I see. That's a distinction I missed looking through proto3's documentation and discussions around [nullability](https://github.com/google/protobuf/issues/1606).

I believe this is a mistake many will also make by looking at the documentation that gets generated.
Keeping `optional` implies fields in proto3 can be required. Would it then be truer to remove the column altogether if compiling from proto3?

**Comment by rmartin7c** [comment]
I don't think we can drop the "Label" column entirely, because the `repeated` label is still valid in proto3.

**Comment by jdaily** [comment]
Yea, much easier to leave this alone.

Still extremely grateful this project exists. Much easier for technical non-dev consumers to read than raw proto.

**Comment by rmartin7c** [comment]
Agreed, this plugin has been a huge help for our teams working with protobuf and gRPC. Muchos kudos to @estan !

**Comment by estan** [comment]
Thanks for your kind words. I unfortunately don't have time anymore to give this tool the love it needs (too busy at work, and not using protobuf anymore).

From what I've heard, the tool "works" when compiled against protobuf 3, but I'm now open to pull requests to fix this issue and improve the experience with protobuf 3.

I think what needs to be done is: If the tool is built against protobuf 3, it should default to a new "protobuf 3 mode", where it behaves differently, adding support for new stuff in 3 where it makes sense, possibly uses protobuf 3-specific built-in templates (e.g. taking into account the changes regarding optional/required).

If it's built against protobuf 2, it should work like it does now.

If building against protobuf 3, the user should be able to force the "protobuf 2" mode if he/she wants.

There should be additional CI jobs added to Travis and Appveyor which tests the tool against protobuf 3.

So quite some work to do, but I'm hoping that maybe someone using the tool will step up. I'm willing the review the changes. And if someone makes a good pull request for this, I think I'd consider relieving maintainership of the tool to that person.

**Comment by estan** [comment]
Looking at https://github.com/google/protobuf/releases/tag/v3.0.0, this is the list of changes that I think may have an influence on how the tool should work when `syntax = "proto3"` (better to check that I realized now, instead of the "modes" I talked about above):

* Removal of field presence logic for primitive value fields, removal of required fields, and removal of default values.
* Removal of unknown fields.
* Removal of extensions, which are instead replaced by a new standard
type called Any.
* Fix semantics for unknown enum values.
* Addition of maps (back-ported to proto2)
* Addition of a small set of standard types for representation of time,
dynamic data, etc (back-ported to proto2)
* A new notion "syntax" is introduced to specify whether a .proto file uses proto2 or proto3.
* Explicit "optional" keyword are disallowed in proto3 syntax, as fields are
optional by default; required fields are no longer supported.
* Removed non-zero default values and field presence logic for non-message
fields. e.g. has_xxx() methods are removed; primitive fields set to default
values (0 for numeric fields, empty for string/bytes fields) will be skipped
during serialization.
* Group fields are no longer supported in proto3 syntax.
* Added well-known type protos (any.proto, empty.proto, timestamp.proto,
duration.proto, etc.). Users can import and use these protos just like
regular proto files. Additional runtime support are available for each
language.
* Added a "reserved" keyword in both proto2 and proto3 syntax. Users can use
this keyword to declare reserved field numbers and names to prevent them
from being reused by other fields in the same message.
* Added a new field option "json_name". By default proto field names are
converted to "lowerCamelCase" in proto3 JSON format. This option can be
used to override this behavior and specify a different JSON name for the
field.

**Comment by estan** [comment]
Please see my recent addition to the README.md, copied below. My sincerest apologies for this.

```
To all users of `protoc-gen-doc`: This project is now unmaintained and
seeking a new maintainer. The reason for this is two-fold:

1. I'm not using Protocol Buffers myself anymore, and haven't done so
   for years.

2. I'm too busy with work and other projects to keep developing
   the tool, deal with feature requests and PRs.

Too all those who have outstanding pull requests and/or issues filed:
I'm really sorry, and thank you so much for your contributions, but I
simply don't have time for the project anymore, even if it is quite
low-maintenance.

Are you a user of `protoc-gen-doc` who feel you could take over? Great!
Please get in touch with me privately and we can discuss how to best
proceed (GitHub forking and transferring of Travis CI / AppVeyor / Open
Build Service accounts). The code is quite simple and only moderate C++
skills and some familiarity with Qt is needed.

Again, to all users: I'm sorry for this inconvenience, but it would be
dishonest of me to continue claiming maintainership of this project
when I don't have the time anymore.
```
