### ISSUE TITLE
apt repository public key expired

### ISSUE THREAD

**Issue by sla89** [pseudomuto/protoc-gen-doc#295]
I get the following error:

```
W: GPG error: http://download.opensuse.org/repositories/home:/estan:/protoc-gen-doc/xUbuntu_16.04  Release: The following signatures were invalid: KEYEXPIRED 1497438657
W: The repository 'http://download.opensuse.org/repositories/home:/estan:/protoc-gen-doc/xUbuntu_16.04  Release' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
```

Can you please fix that?

**Comment by aschrijver** [comment]
Yes, this is problematic. Cannot install on TravisCI:

```
Reading package lists... Done
W: http://dl.hhvm.com/ubuntu/dists/trusty/InRelease: Signature by key 36AEF64D0207E7EEE352D4875A16E7281BE7A449 uses weak digest algorithm (SHA1)
W: GPG error: http://download.opensuse.org/repositories/home:/estan:/protoc-gen-doc/xUbuntu_14.04  Release: The following signatures were invalid: KEYEXPIRED 1497438657
W: The repository 'http://download.opensuse.org/repositories/home:/estan:/protoc-gen-doc/xUbuntu_14.04  Release' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/Release.gpg: Signature by key 15866BAFD9BCC4F3C1E0DFC7D69548E1C17EAB57 uses weak digest algorithm (SHA1)
0.52s$ sudo apt-get install protoc-gen-doc
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libprotobuf8 libprotoc8 libqt5core5a
The following NEW packages will be installed:
  libprotobuf8 libprotoc8 libqt5core5a protoc-gen-doc
0 upgraded, 4 newly installed, 0 to remove and 35 not upgraded.
Need to get 2,326 kB of archives.
After this operation, 7,423 kB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  protoc-gen-doc
E: There were unauthenticated packages and -y was used without --allow-unauthenticated
```

**Comment by estan** [comment]
Hi, I'm the previous maintainer of `protoc-gen-doc` and the repository links still seems to point at my repositories at OBS (Open Build Service), which I had planned on taking down now that @pseudomuto is the new maintainer.

But for now, I've re-signed the GPG key on OBS with `osc signkey --extend`, to extend the expiration date, and triggered a re-build of all packages. So you should no longer be getting this problem.

However, what really should be done is that @pseudomuto, the new maintainer, should set up his own project and package at OBS, and publish the packages there.

@pseudomuto: Here's what you'll need to do (the OBS web interface is a little wonky):

1. Create an account at OBS (https://build.opensuse.org/).
2. Create a subproject "protoc-gen-doc" under your Home project:
![1_create_subproject_under_home_project](https://user-images.githubusercontent.com/86675/28489945-0edff0ae-6ecf-11e7-8671-1142d3502c6c.png)
3. Add repositories/architectures to the "protoc-gen-doc" subproject (below shows the one I've added):
![3_add_repositories](https://user-images.githubusercontent.com/86675/28489966-a90edb2c-6ecf-11e7-93e9-729af6b12d6d.png)
4. Create a package "protoc-gen-doc" under the "protoc-gen-doc" subproject:
![2_create_package](https://user-images.githubusercontent.com/86675/28489957-6201dcc0-6ecf-11e7-9c41-095d6799e21c.png)
5. **Optional but recommended**: Finalize the updates to the files in the `pkg` directory, as some of them still point the the `estan/protoc-gen-doc` GitHub repo (which still works since it redirects to yours). These files should be fixed:
```
estan@newton:~/protoc-gen-doc$ grep -r estan pkg
pkg/protoc-gen-doc.spec:Url:            http://github.com/estan/protoc-gen-doc
pkg/protoc-gen-doc.spec:Source0:        https://github.com/estan/protoc-gen-doc/archive/v%{version}.tar.gz
pkg/debian.control:Homepage: https://github.com/estan/protoc-gen-doc
pkg/_service:    <param name="path">estan/protoc-gen-doc/archive/v0.9.tar.gz</param>
pkg/PKGBUILD:url='https://github.com/estan/protoc-gen-doc'
estan@newton:~/protoc-gen-doc$
```
6. Upload the `_service` file to the "protoc-gen-doc" package at OBS:
![4_upload_service_file](https://user-images.githubusercontent.com/86675/28489992-4a761cb4-6ed0-11e7-926b-1d238ab22db6.png)

The other files you see in the screenshot will be pulled automatically by OBS when you add the `_service` file, and package builds for the configured repositories/architectures should start automatically.

7. Update the repo links in `README.md` and the OBS link in `Release Checklist` in the wiki.

**Comment by aschrijver** [comment]
@estan Thanks a LOT for your extensive explanation and your help!! :+1: :+1: 

(Just FYI) I am testing out various options to have richer output (inline html or markdown bold, italic, code, link, etc. formatting) and found no option to be viable currently due to bugs.

You can see my findings on:
https://github.com/aschrijver/hypercore-protocol/tree/feature/document-generator

**Comment by estan** [comment]
@aschrijver Alright. I'm no longer developing `protoc-gen-doc` and have passed on the maintainership to @pseudomuto. I hope you figure out some way to get the output you want.

**Comment by aschrijver** [comment]
Sure, I'll file some issues, no problem. May good dev experiences find you forever! :raised_hand_with_fingers_splayed:

**Comment by estan** [comment]
@pseudomuto I'll let you close this issue. Let me know how setting up the OBS project/package goes.

**Comment by pseudomuto** [comment]
Will do! Thanks for the details man!

**Comment by pseudomuto** [comment]
I'm going to close this since this project is no longer available as an apt package. See README for other installation options.
