### ISSUE TITLE
Release for Debian 9 (stretch)

### ISSUE THREAD

**Issue by gfecher** [pseudomuto/protoc-gen-doc#297]
Could you please create a release against Debian 9 (stretch) and libprotobuf10, libprotoc10 and install it under http://download.opensuse.org/repositories/home:/estan:/protoc-gen-doc/Debian_9.0/?

Many thanks

**Comment by pseudomuto** [comment]
Hey @gfecher, I know it's been a long time since you opened this. The project has been ported to go since, and no long publishes a deb package.

However, you should be able to do one of the following:

* Untar the latest release from https://github.com/pseudomuto/protoc-gen-doc/releases/download/v1.0.0/protoc-gen-doc-1.0.0.linux-amd64.go1.9.tar.gz
* Install with `go get`, though that'll be master

**Comment by gfecher** [comment]
Hello, thanks, I'll take a look at the go project, but I have since started using https://github.com/protostuff/protostuff-compiler to generate documentation as it integrates better into our java (maven) build process.
