### ISSUE TITLE
Masterminds/sprig is broken

### ISSUE THREAD

**Issue by erikh** [pseudomuto/protoc-gen-doc#402]
breaks master installations. I filed https://github.com/Masterminds/sprig/pull/179 to resolve it.

**Comment by mattfarina** [comment]
@erikh The go.mod file has `github.com/Masterminds/semver` at version `v1.4.2`. The change that is breaking this is for the tip of master which is development of the 3.x version. How are you installing/updating proto-gen-doc? There appears to be a version mismatch.

**Comment by pauljz** [comment]
This was reproducible for me with the go get command from the [README.md installation section](https://github.com/pseudomuto/protoc-gen-doc#installation).

```
# go version
go version go1.12.9 darwin/amd64

# go get -u github.com/pseudomuto/protoc-gen-doc/cmd/protoc-gen-doc
# github.com/Masterminds/sprig
../../go/src/github.com/Masterminds/sprig/semver.go:22:2: cannot use semver.Version as type *semver.Version in return argument
```

**Comment by mattfarina** [comment]
&tldr; semver has been updated to the v1 Go API interface so the install problems should go away.

The long form of this is that the problem arouse because a new major version of semver is in development. A Go API changed. `go get` was still trying to pull from the tip of master rather than a release version. Even though one is specified in the `go.mod` file. So, things broke. This isn't so much a problem with semver as it is with `go get`.

This issue should be able to be closed for a variety of reasons.

**Comment by erikh** [comment]
thanks, I've confirmed this is resolved and will be closing this ticket.
